config/routes.rb
# this file: config/routes.rb

# http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get '/'             => 'sites#home'

  # shorter way of defining routes
  # also enables to use all the Rails path helpers
  resources :projects, only: [:index, :show, :new, :create, :edit, :update] do
    resources :entries, only: [:index, :destroy, :new, :create]
  end

  resources :people, only: [:new, :create]

  # routes defined by hand (error prone)
  # get  '/projects/new'      => 'projects#new'
  # get  '/projects/:id'      => 'projects#show'
  # put  '/projects/:id'      => 'projects#update'
  # post '/projects'          => 'projects#create'
  # get  '/projects'          => 'projects#index'
  # get  '/projects/:id/edit' => 'projects#edit'
end

app/models/entry.rb
# app/models/entry.rb

class Entry < ActiveRecord::Base
  belongs_to :project
  validates  :project, presence: true

  # http://guides.rubyonrails.org/active_record_validations.html
  validates :hours,   numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 24 }
  validates :minutes, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 60 }
  validates :date, presence: true
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :person
  belongs_to :project
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :participations, dependent: :destroy
  has_many :projects, through: :participations

  # accepts_nested_attributes_for :participations
end

app/models/project.rb
# app/models/project.rb

class Project < ActiveRecord::Base
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :logo, content_type: %r{\Aimage\/.*\Z}

  has_many :entries, dependent: :destroy  # destroy all entries when the project is destroyed
  has_many :participations, dependent: :destroy
  has_many :people, through: :participations

  validates :name, presence: true, uniqueness: true

  def self.iron_find(date = Time.zone.today)
    order("name ASC").where("created_at > ?", date).limit(10)
  end

  def self.clean_old(date = 1.week.ago)
    where("created_at < ?", date).destroy_all
  end

  def self.last_created(n)
    # raise ArgumentError unless n.is_a? Integer && n.in(1..25)
    order(created_at: :desc).limit(n)
  end

  def total_hours_in_month(month = Time.zone.today.month, year = Time.zone.today.year)
    dt = Time.zone.parse("#{year}-#{month}-1")

    entries.where("date > ?", dt).where("date < ?", dt.end_of_month).sum(:hours)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def render_404(params)
    # this line will only appear in your logs
    Rails.logger.warn("Tried to access #{params} which did not exist.")

    render "layouts/404"
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @entries = @project.entries.where("date >= ?", 1.month.ago)
  end

  def new
    @project = Project.find(params[:project_id])
    @entry = @project.entries.new
  end

  def create
    @project = Project.find(params[:project_id])
    @entry = @project.entries.new(entry_params)

    if @entry.valid?
      @entry.save
      redirect_to project_entries_path(@project), notice: "Entry successfully added!"
    else
      render :new
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @entry = Entry.find_by(id: params[:id]).try(:destroy)

    redirect_to project_entries_path(@project), notice: "Entry #{@entry.inspect} was destroyed."
  end

  private

  def entry_params
    params.require(:entry).permit(:hours, :minutes, :date)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def new
    @person = Person.new
    @projects = Project.pluck(:name, :id)
  end

  def create
    @person  = Person.new(name: person_params[:name])
    @project = Project.find(params[:project_id])

    if @person.valid? && @project.present?
      @person.save

      @project.people << @person

      redirect_to project_path(@project), notice: "#{@person.name} added to this project."
    else
      render :new
    end
  end

  private

  def person_params
    params.require(:person).permit(:name) #, participation_attributes: [:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.last_created(10)
  end

  def show
    @project = Project.find_by(id: params[:id]) ||
      render_404(params)
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find_by(id: params[:id]) ||
      render_404(params)
  end

  def create
    @project = Project.new(project_params)

    if @project.valid?
      @project.save
      redirect_to projects_path, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    @project = Project.find_by(id: params[:id])

    if @project.update_attributes(project_params)
      redirect_to projects_path, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end


  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :description, :logo)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_form.html.erb
<!-- views/entries/_form.html.erb -->

<%= form_for([project, entry]) do |f| %>

  <%= render 'layouts/errors', model: entry %>

  <div class="field">
    <%= f.label :hours %>
    <br />
    <%= f.number_field :hours, min: 0 %>
  </div>

  <div class="field">
    <%= f.label :minutes %>
    <br />
    <%= f.number_field :minutes, in: 0..59 %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <br />
    <%= f.date_field :date, value: Time.zone.today.iso8601 %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/entries/index.html.erb
<!-- app/views/entries/index.html.erb -->

<h1><%= @project.name %></h1>
<ul>
  <% @entries.each do |entry| %>
    <li>
      <%= entry.hours %> h
      <%= entry.minutes %> m -
      <%= entry.date.strftime("%d.%m.%Y") %>
      |
      <%= link_to 'Delete', project_entries_path(@project, entry), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

<p>Hours worked this month: <%= @project.total_hours_in_month %></p>

<%= link_to "Add new entry", new_project_entry_path(@project) %>

app/views/entries/new.html.erb
<!-- app/views/entries/new.html.erb -->

Add an entry:

<%= render 'form', entry: @entry, project: @project %>

app/views/layouts/404.html.erb
<h2>404 - There is nothing to see here.</h2>

<hr />

Please go back to: <a href="/">start</a>.

app/views/layouts/_errors.html.erb
<!-- This file is: app/views/projects/_errors.html.erb -->

<% if model.errors.any? %>
  <div class="model-errors">
    <h2>
      <%= pluralize(model.errors.count, "error") %>
      <%= "prohibited this #{model.class.name} from being saved:" %>
    </h2>

    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!-- This file is: app/views/layouts/application.html.erb -->

<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-info" %>
  <% end %>

  <h1>Timetracking tool</h1>

  <%= yield %>

  <hr />
  <%= link_to "List of all projects", projects_path %>
  |
  <%= link_to "New projects", new_project_path %>
</body>
</html>

app/views/people/new.html.erb
<!-- app/views/people/new.html.erb -->

<%= form_for(@person) do |f| %>

  <%= render 'layouts/errors', model: @person %>

  <div class="field">
    <%= f.label :name %>
    <br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= label_tag :project %>
    <br />
    <%= select_tag(:project_id, options_for_select(@projects)) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/projects/_form.html.erb
<!-- views/projects/_form.html.erb -->

<%= form_for(project, html: { multipart: true }) do |f| %>

  <%= render 'layouts/errors', model: project %>

  <div class="field">
    <%= f.label :name %>
    <br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :logo %>
    <br />
    <%= f.file_field :logo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/projects/_links.html.erb
<!-- app/views/projects/_links.html.erb -->

<span class="links">
  |
  <%= link_to "Show all entries", project_entries_path(project)  %>
  |
  <%= link_to "Edit", edit_project_path(project) %>
</span>

app/views/projects/edit.html.erb
<!-- views/projects/edit.html.erb -->

<h2>Edit Project</h2>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<!-- app/views/projects/index.html.erb -->

<h2> All the Projects </h2>

<ul>
  <% @projects.each do |project| %>
    <li class="project">
      <%= link_to project.name, project_path(project) %>

      <% if project.description.present? %>
        -
        <%= project.description %>
      <% end %>

      <%= render "links", project: project %>
    </li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<!-- views/projects/new.html.erb -->

<h2>New Project</h2>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<!-- app/views/projects/show.html.erb -->

<p class="project">
  <%= image_tag @project.logo.url(:thumb) %>

  <%= @project.name %>

  <% if @project.description.present? %>
    -
    <%= @project.description %>
  <% end %>

  <%= render "links", project: @project %>

  <h4>Participants: </h4>
  <% @project.people.each do |person| %>
    <p><%= person.name %></p>
  <% end %>

  <%= link_to "Add new participant", new_person_path %>
</p>

app/views/sites/home.html.erb
<h2>Welcome</h2>

<p> Running in the <b><%= Rails.env %></b> environment </p>